version: '3.7'
services:
  pingwave:
    build: .
    volumes:
      - ./config.hcl:/etc/pingwave.hcl
      - /home/ghjnut/go/bin/pingwave:/usr/local/bin/pingwave
    command: -config-file /etc/pingwave.hcl -statsd graphite:8125
    networks:
      - graphite
    depends_on:
      - graphite

  pingwave_dev:
    build:
      context: .
      target: builder
    volumes:
      - .:/go/src/github.com/ghjnut/pingwave
    entrypoint: sh
    networks:
      - graphite
    depends_on:
      - graphite
      - grafana

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_storage:/var/lib/grafana
    ports:
      - "8082:3000"
    networks:
      - graphite
    depends_on:
      - graphite

  graphite:
    image: graphiteapp/graphite-statsd
    volumes:
      - graphite_conf:/opt/graphite/conf
      - graphite_storage:/opt/graphite/storage
      - statsd_conf:/opt/statsd/config
    networks: 
      - graphite
    ports:
      - "2003:2003"
      - "8081:8080"

volumes:
  grafana_storage:
  graphite_conf:
  graphite_storage:
  statsd_conf:

networks:
  graphite:
